// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0e134bb8-43e9-485a-b6a6-5bb0098a390c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2RRQEFGTF",
    "aws_user_pools_web_client_id": "3b4s3ki7577p4u0ainje8gsp1r",
    "aws_content_delivery_bucket": "semanticsearchspike-20180916205559--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://semanticsearchspike-20180916205559--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://yagish2ud5aoxdqvvaknepm6ve.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "semanticsearchdocs",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
